name = "WebAssets"
uuid = "5318a24a-cfbb-471b-80de-2ec25d7c2d8b"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]
version = "0.2.1"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[compat]
Scratch = "1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
